services:
    _defaults:
        autowire: true
        autoconfigure: true

    MarcinOrlowski\DiscoDevBar\:
        resource: '../../src/'
        exclude: '../../src/{DependencyInjection,Dto}'

    MarcinOrlowski\DiscoDevBar\Service\DiscoDevBarService:
        arguments:
            $projectDir: '%kernel.project_dir%'
            $fontAwesomeEnabled: '%disco_dev_bar.font_awesome.enabled%'
            $fontAwesomeVersion: '%disco_dev_bar.font_awesome.version%'

    MarcinOrlowski\DiscoDevBar\Twig\DiscoDevBarExtension:
        tags: ['twig.extension']
