##################################################################################
#
# @author    Marcin Orlowski <mail (#) marcinOrlowski (.) com>
#
##################################################################################

name: "CSS Lint"

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
      - "dev"

jobs:
  analyze_sources:
    name: "Check if there any CSS code to work on?"
    runs-on: ubuntu-latest

    outputs:
      # Export 'filter' step check result so next step can use it.
      run_action: ${{ steps.filter.outputs.src }}
      # These are source files matching our filter that are affected by the PR.
      changed_files: ${{ steps.filter.outputs.src_files }}

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: "Checkout sources"
        uses: actions/checkout@v4

      # https://github.com/marketplace/actions/paths-changes-filter
      - name: "Look for changes that matters for us…"
        uses: dorny/paths-filter@v3
        id: filter
        with:
          # Token is optional for public repos, but required for private repos
          token: ${{ secrets.GITHUB_TOKEN }}
          list-files: 'escape'
          filters: |
            src:
              - 'Resources/public/*.css'

      - name: "Will action step be run?"
        run: |
          found="NO"
          [[ ${{ steps.filter.outputs.src }} == 'true' ]] && found="YES"
          echo "run_action=${found}" >> $GITHUB_OUTPUT
          echo -e "\n****************************************\n"
          echo "${found}"
          echo -e "****************************************"

  check:
    name: "Run tools…"
    # Will run only if analyze_sources determined it is needed.
    needs: analyze_sources
    if: needs.analyze_sources.outputs.run_action == 'true'

    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: "Checkout repository…"
        uses: actions/checkout@v4

      # https://github.com/marketplace/actions/setup-node
      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: "Installing dependencies…"
        run: npm install

      - name: "Running Stylelint…"
        run: npx stylelint "Resources/public/*.css"
